name: test

on: [pull_request, push]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox -e flake8
        run: tox
        env:
          TOXENV: flake8

  test:
    name: unittests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toxenv:
            - py37-dj22-wt211
            - py37-dj3-wt211
            - py37-dj31-wt211
            - py38-dj22-wt211
            - py38-dj3-wt211
            - py38-dj31-wt211
            - py37-dj22-wt212
            - py37-dj3-wt212
            - py37-dj31-wt212
            - py38-dj22-wt212
            - py38-dj3-wt212
            - py38-dj31-wt212
            - py39-dj22-wt212
            - py39-dj3-wt212
            - py39-dj31-wt212
            - py37-dj22-wt213
            - py37-dj3-wt213
            - py37-dj31-wt213
            - py37-dj32-wt213
            - py38-dj22-wt213
            - py38-dj3-wt213
            - py38-dj31-wt213
            - py38-dj32-wt213
            - py39-dj22-wt213
            - py39-dj3-wt213
            - py39-dj31-wt213
            - py39-dj32-wt213
            - py37-dj3-wt214
            - py37-dj31-wt214
            - py37-dj32-wt214
            - py38-dj3-wt214
            - py38-dj31-wt214
            - py38-dj32-wt214
            - py39-dj3-wt214
            - py39-dj31-wt214
            - py39-dj32-wt214
            - py37-dj3-wt215
            - py37-dj31-wt215
            - py37-dj32-wt215
            - py38-dj3-wt215
            - py38-dj31-wt215
            - py38-dj32-wt215
            - py39-dj3-wt215
            - py39-dj31-wt215
            - py39-dj32-wt215
            - py310-dj3-wt215
            - py310-dj31-wt215
            - py310-dj32-wt215
            - py37-dj32-wt216
            - py37-dj40-wt216
            - py38-dj32-wt216
            - py38-dj40-wt216
            - py39-dj32-wt216
            - py39-dj40-wt216
            - py310-dj32-wt216
            - py310-dj40-wt216
            - py37-dj32-wt3
            - py37-dj40-wt3
            - py38-dj32-wt3
            - py38-dj40-wt3
            - py39-dj32-wt3
            - py39-dj40-wt3
            - py310-dj32-wt3
            - py310-dj40-wt3
            - py38-dj32-wt4
            - py38-dj40-wt4
            - py38-dj41-wt4
            - py39-dj32-wt4
            - py39-dj40-wt4
            - py39-dj41-wt4
            - py310-dj32-wt4
            - py310-dj40-wt4
            - py310-dj41-wt4
        include:
            - toxenv: py37-dj22-wt211
              python-version: 3.7
            - toxenv: py37-dj3-wt211
              python-version: 3.7
            - toxenv: py37-dj31-wt211
              python-version: 3.7

            - toxenv: py38-dj22-wt211
              python-version: 3.8
            - toxenv: py38-dj3-wt211
              python-version: 3.8
            - toxenv: py38-dj31-wt211
              python-version: 3.8

            - toxenv: py37-dj22-wt212
              python-version: 3.7
            - toxenv: py37-dj3-wt212
              python-version: 3.7
            - toxenv: py37-dj31-wt212
              python-version: 3.7

            - toxenv: py38-dj22-wt212
              python-version: 3.8
            - toxenv: py38-dj3-wt212
              python-version: 3.8
            - toxenv: py38-dj31-wt212
              python-version: 3.8

            - toxenv: py39-dj22-wt212
              python-version: 3.9
            - toxenv: py39-dj3-wt212
              python-version: 3.9
            - toxenv: py39-dj31-wt212
              python-version: 3.9

            - toxenv: py37-dj22-wt213
              python-version: 3.7
            - toxenv: py37-dj3-wt213
              python-version: 3.7
            - toxenv: py37-dj31-wt213
              python-version: 3.7
            - toxenv: py37-dj32-wt213
              python-version: 3.7

            - toxenv: py38-dj22-wt213
              python-version: 3.8
            - toxenv: py38-dj3-wt213
              python-version: 3.8
            - toxenv: py38-dj31-wt213
              python-version: 3.8
            - toxenv: py38-dj32-wt213
              python-version: 3.8

            - toxenv: py39-dj22-wt213
              python-version: 3.9
            - toxenv: py39-dj3-wt213
              python-version: 3.9
            - toxenv: py39-dj31-wt213
              python-version: 3.9
            - toxenv: py39-dj32-wt213
              python-version: 3.9

            - toxenv: py37-dj3-wt214
              python-version: 3.7
            - toxenv: py37-dj31-wt214
              python-version: 3.7
            - toxenv: py37-dj32-wt214
              python-version: 3.7

            - toxenv: py38-dj3-wt214
              python-version: 3.8
            - toxenv: py38-dj31-wt214
              python-version: 3.8
            - toxenv: py38-dj32-wt214
              python-version: 3.8

            - toxenv: py39-dj3-wt214
              python-version: 3.9
            - toxenv: py39-dj31-wt214
              python-version: 3.9
            - toxenv: py39-dj32-wt214
              python-version: 3.9

            - toxenv: py37-dj3-wt215
              python-version: 3.7
            - toxenv: py37-dj31-wt215
              python-version: 3.7
            - toxenv: py37-dj32-wt215
              python-version: 3.7

            - toxenv: py38-dj3-wt215
              python-version: 3.8
            - toxenv: py38-dj31-wt215
              python-version: 3.8
            - toxenv: py38-dj32-wt215
              python-version: 3.8

            - toxenv: py39-dj3-wt215
              python-version: 3.9
            - toxenv: py39-dj31-wt215
              python-version: 3.9
            - toxenv: py39-dj32-wt215
              python-version: 3.9

            - toxenv: py310-dj3-wt215
              python-version: 3.10
            - toxenv: py310-dj31-wt215
              python-version: 3.10
            - toxenv: py310-dj32-wt215
              python-version: 3.10

            - toxenv: py37-dj32-wt216
              python-version: 3.7
            - toxenv: py37-dj40-wt216
              python-version: 3.7

            - toxenv: py38-dj32-wt216
              python-version: 3.8
            - toxenv: py38-dj40-wt216
              python-version: 3.8

            - toxenv: py39-dj32-wt216
              python-version: 3.9
            - toxenv: py39-dj40-wt216
              python-version: 3.9

            - toxenv: py310-dj32-wt216
              python-version: 3.10
            - toxenv: py310-dj40-wt216
              python-version: 3.10

            - toxenv: py37-dj32-wt3
              python-version: 3.7
            - toxenv: py37-dj40-wt3
              python-version: 3.7

            - toxenv: py38-dj32-wt3
              python-version: 3.8
            - toxenv: py38-dj40-wt3
              python-version: 3.8

            - toxenv: py39-dj32-wt3
              python-version: 3.9
            - toxenv: py39-dj40-wt3
              python-version: 3.9

            - toxenv: py310-dj32-wt3
              python-version: 3.10
            - toxenv: py310-dj40-wt3
              python-version: 3.10

            - toxenv: py38-dj32-wt4
              python-version: 3.8
            - toxenv: py38-dj40-wt4
              python-version: 3.8
            - toxenv: py38-dj41-wt4
              python-version: 3.8

            - toxenv: py39-dj32-wt4
              python-version: 3.9
            - toxenv: py39-dj40-wt4
              python-version: 3.9
            - toxenv: py39-dj41-wt4
              python-version: 3.9

            - toxenv: py310-dj32-wt4
              python-version: 3.10
            - toxenv: py310-dj40-wt4
              python-version: 3.10
            - toxenv: py310-dj41-wt4
              python-version: 3.10

    services:
      postgres:
        image: postgres:10.8
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: |
            tox
        env:
          DATABASE_HOST: localhost
          DATABASE_USER: postgres
          DATABASE_PASS: postgres
          TOXENV: ${{ matrix.toxenv }}
