name: Tox

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Lint the codebase
        run: tox -e flake8

  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
        ports:
          - 5432:5432

    strategy:
      max-parallel: 4
      matrix:
        include:
          # Wagtail 2.7 LTS
          - python-version: 3.6
            tox-env: py36-dj2-wt27
          - python-version: 3.7
            tox-env: py37-dj2-wt27
          - python-version: 3.8
            tox-env: py38-dj2-wt27

          - python-version: 3.6
            tox-env: py36-dj21-wt27
          - python-version: 3.7
            tox-env: py37-dj21-wt27
          - python-version: 3.8
            tox-env: py38-dj21-wt27

          - python-version: 3.6
            tox-env: py36-dj22-wt27
          - python-version: 3.7
            tox-env: py37-dj22-wt27
          - python-version: 3.8
            tox-env: py38-dj22-wt27

          # Wagtail 2.10
          - python-version: 3.6
            tox-env: py36-dj21-wt210
          - python-version: 3.7
            tox-env: py37-dj21-wt210
          - python-version: 3.8
            tox-env: py38-dj21-wt210

          - python-version: 3.6
            tox-env: py36-dj22-wt210
          - python-version: 3.7
            tox-env: py37-dj22-wt210
          - python: 3.8
            tox-env: py38-dj22-wt210

          - python-version: 3.6
            tox-env: py36-dj3-wt210
          - python-version: 3.7
            tox-env: py37-dj3-wt210
          - python-version: 3.8
            tox-env: py38-dj3-wt210

    steps:
    - uses: actions/checkout@v2
    - name: Setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip tox
    - name: Test against ${{matrix.tox-env}}
      env:
        DATABASE_NAME: postgres
        DATABASE_USER: postgres
        DATABASE_PASS: postgres
      run: tox -e ${{ matrix.tox-env }}
