name: test

on: [pull_request, push]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox -e flake8
        run: tox
        env:
          TOXENV: flake8

  test:
    name: unittests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toxenv:
            - py36-dj22-wt211
            - py36-dj3-wt211
            - py36-dj31-wt211
            - py37-dj22-wt211
            - py37-dj3-wt211
            - py37-dj31-wt211
            - py38-dj22-wt211
            - py38-dj3-wt211
            - py38-dj31-wt211
        include:
            - toxenv: py36-dj22-wt211
              python-version: 3.6
            - toxenv: py36-dj3-wt211
              python-version: 3.6
            - toxenv: py36-dj31-wt211
              python-version: 3.6

            - toxenv: py37-dj22-wt211
              python-version: 3.7
            - toxenv: py37-dj3-wt211
              python-version: 3.7
            - toxenv: py37-dj31-wt211
              python-version: 3.7

            - toxenv: py38-dj22-wt211
              python-version: 3.8
            - toxenv: py38-dj3-wt211
              python-version: 3.8
            - toxenv: py38-dj31-wt211
              python-version: 3.8

    services:
      postgres:
        image: postgres:10.8
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: |
            tox
        env:
          DATABASE_HOST: localhost
          DATABASE_USER: postgres
          DATABASE_PASS: postgres
          TOXENV: ${{ matrix.toxenv }}
